### ISSUE TITLE
depricatedな呼び出し

### ISSUE THREAD

**Issue by marmot1123** [b4b4r07/brionac#1]
Homebrewが更新されたことでsha1関連などのいくつかの呼び出しがdepricatedになったようです。
すでに確認されているかもしれませんが、Homebrewの警告文を貼り付けておきます。
対応が可能なようでしたらお願いします。

```
Warning: Calling Hardware.is_64_bit? is deprecated!
Use Hardware::CPU.is_64_bit? instead.
/usr/local/Library/Taps/b4b4r07/homebrew-brionac/brionac.rb:7:in `<class:Brionac>'
Please report this to the b4b4r07/brionac tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/b4b4r07/homebrew-brionac/brionac.rb:9:in `<class:Brionac>'
Please report this to the b4b4r07/brionac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/b4b4r07/homebrew-brionac/brionac.rb:9:in `<class:Brionac>'
Please report this to the b4b4r07/brionac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/b4b4r07/homebrew-brionac/brionac.rb:9:in `<class:Brionac>'
Please report this to the b4b4r07/brionac tap!
```

**Comment by babarot** [comment]
Duplicate #2
